# Generated by Django 3.2 on 2023-06-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensordata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity_val', models.CharField(max_length=20)),
                ('temperature_val', models.CharField(max_length=30)),
                ('moisture_val', models.CharField(max_length=30)),
                ('waterLevel_val', models.CharField(default=0, max_length=30)),
            ],
        ),
    ]
